class CreateSubjects < ActiveRecord::Migration[5.2]
  def change
    create_table :subjects do |t|
      t.boolean :correct, default: false
      t.integer :id_professor
      t.string :nome_professor
      t.string :escola
      t.string :nome_aluno1_p1
      t.string :nome_aluno2_p1
      t.string :nome_aluno1_p2
      t.string :nome_aluno2_p2
      t.string :nome_aluno1_p3
      t.string :nome_aluno2_p3
      t.string :nome_aluno1_p4
      t.string :nome_aluno2_p4
      t.string :nome_aluno1_p5
      t.string :nome_aluno2_p5
      t.string :nome_aluno1_p6
      t.string :nome_aluno2_p6
      t.string :nome_aluno1_p7
      t.string :nome_aluno2_p7
      t.string :nome_aluno1_p8
      t.string :nome_aluno2_p8
      t.string :nome_aluno1_p9
      t.string :nome_aluno2_p9
      t.string :nome_aluno1_p10
      t.string :nome_aluno2_p10
      t.string :nome_aluno1_p11
      t.string :nome_aluno2_p11
      t.string :nome_aluno1_p12
      t.string :nome_aluno2_p12
      t.string :nome_aluno1_p13
      t.string :nome_aluno2_p13
      t.string :nome_aluno1_p14
      t.string :nome_aluno2_p14
      t.string :nome_aluno1_p15
      t.string :nome_aluno2_p15
      t.string :nome_aluno1_p16
      t.string :nome_aluno2_p16
      t.string :nome_aluno1_p17
      t.string :nome_aluno2_p17
      t.string :nome_aluno1_p18
      t.string :nome_aluno2_p18
      t.string :nome_aluno1_p19
      t.string :nome_aluno2_p19
      t.string :nome_aluno1_p20
      t.string :nome_aluno2_p20
      t.string :nome_aluno1_p21
      t.string :nome_aluno2_p21
      t.string :nome_aluno1_p22
      t.string :nome_aluno2_p22
      t.string :nome_aluno1_p23
      t.string :nome_aluno2_p23
      t.string :nome_aluno1_p24
      t.string :nome_aluno2_p24
      t.string :nome_aluno1_p25
      t.string :nome_aluno2_p25
      t.string :nome_aluno1_p26
      t.string :nome_aluno2_p26
      t.string :nome_aluno1_p27
      t.string :nome_aluno2_p27
      t.string :nome_aluno1_p28
      t.string :nome_aluno2_p28
      t.string :nome_aluno1_p29
      t.string :nome_aluno2_p29
      t.string :nome_aluno1_p30
      t.string :nome_aluno2_p30
      t.string :nome_aluno1_p31
      t.string :nome_aluno2_p31
      t.string :nome_aluno1_p32
      t.string :nome_aluno2_p32
      t.string :nome_aluno1_p33
      t.string :nome_aluno2_p33
      t.string :nome_aluno1_p34
      t.string :nome_aluno2_p34
      t.string :nome_aluno1_p35
      t.string :nome_aluno2_p35
      t.string :nome_aluno1_p36
      t.string :nome_aluno2_p36
      t.string :nome_aluno1_p37
      t.string :nome_aluno2_p37
      t.string :nome_aluno1_p38
      t.string :nome_aluno2_p38
      t.string :nome_aluno1_p39
      t.string :nome_aluno2_p39
      t.string :nome_aluno1_p40
      t.string :nome_aluno2_p40
      t.string :nome_aluno1_p41
      t.string :nome_aluno2_p41
      t.string :nome_aluno1_p42
      t.string :nome_aluno2_p42
      t.string :nome_aluno1_p43
      t.string :nome_aluno2_p43
      t.string :nome_aluno1_p44
      t.string :nome_aluno2_p44
      t.string :nome_aluno1_p45
      t.string :nome_aluno2_p45
      t.string :nome_aluno1_p46
      t.string :nome_aluno2_p46
      t.string :nome_aluno1_p47
      t.string :nome_aluno2_p47
      t.string :nome_aluno1_p48
      t.string :nome_aluno2_p48
      t.string :nome_aluno1_p49
      t.string :nome_aluno2_p49
      t.string :nome_aluno1_p50
      t.string :nome_aluno2_p50

      t.timestamps
    end
  end
end
